name: Android AutoFix (Build APK)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Set Android dir
        id: cfg
        run: echo "dir=GroceryMobileApp" >> "$GITHUB_OUTPUT"

      - name: Patch namespace + exported
        working-directory: ${{ steps.cfg.outputs.dir }}
        run: |
          MF="app/src/main/AndroidManifest.xml"
          # Tambah namespace kalau tak ada
          if ! grep -q "namespace" app/build.gradle; then
            sed -i "/android {/a \    namespace \"codecanyon.grocery\"" app/build.gradle
          fi
          # Tambah exported ke activity & service
          sed -i -E '/<activity /{s|<activity |<activity android:exported="true" |g}' "$MF"
          sed -i -E '/<service /{s|<service |<service android:exported="false" |g}' "$MF"

      - name: Grant execute for gradlew
        working-directory: ${{ steps.cfg.outputs.dir }}
        run: chmod +x ./gradlew || true

      - name: Build release APK
        working-directory: ${{ steps.cfg.outputs.dir }}
        run: ./gradlew --no-daemon :app:assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: ${{ steps.cfg.outputs.dir }}/app/build/outputs/apk/release/*.apk
